### ISSUE TITLE
[Suggestion 1] Please add ReadMe to this REPO.

### ISSUE THREAD

**Issue by sanjaypradeep** [javascriptteacher/primary#1]

**Comment by alexmuzenhardt** [comment]
Hi, I will create and add a README to this project.

**Comment by sanjaypradeep** [comment]
+1 @javascriptteacher  

Hi @alexmuzenhardt Please go ahead.

**Comment by osumgbachiamaka** [comment]
it's 12 days already, @alexmuzenhardt are you still adding the Readme file? if not @sanjaypradeep can i work on it

**Comment by sanjaypradeep** [comment]
Hi @osumgbachiamaka - There's a already a basic ReadME file available in PR. Once that is merged, you can go forward and add content - which would be really helpful for others. Much appreciated.

**Comment by sanjaypradeep** [comment]
> Hi @osumgbachiamaka - There's a already a basic ReadME file available in PR. Once that is merged, you can go forward and add content - which would be really helpful for others. Much appreciated.

[Update] - Please go ahead and do missing contents in Readme.

**Comment by ilyosjon09** [comment]
Readme has been created #25 and merged.
