### ISSUE TITLE
What if it returns a `null or empty string or undefined`?

### ISSUE THREAD

**Issue by sanjaypradeep** [javascriptteacher/primary#12]
What if it returns a `null or empty string or undefined`?

Validation would be helpful.

_Originally posted by @sanjaypradeep in https://github.com/javascriptteacher/primary/pull/10_

**Comment by sanjaypradeep** [comment]
Hi @alexmuzenhardt Shall I take this? I've some time now, I can work. 

@javascriptteacher FYI

**Comment by alexmuzenhardt** [comment]
Sure, go ahead. :)

**Comment by sanjaypradeep** [comment]
@alexmuzenhardt Here's the new PR - https://github.com/javascriptteacher/primary/pull/13
