### ISSUE TITLE
[Enhancements] Else block is not really required. 

### ISSUE THREAD

**Issue by sanjaypradeep** [javascriptteacher/primary#16]
https://github.com/javascriptteacher/primary/blob/de971b0452b35e1460fc1d59a06351f1a8e6701e/index.js#L43

**Comment by sanjaypradeep** [comment]
Here's the PR - https://github.com/javascriptteacher/primary/pull/17

**Comment by adinalini** [comment]
This is a nice intro to PRs :)

**Comment by javascriptteacher** [comment]
Please don't create issues for things that are not in Trello.

**Comment by sanjaypradeep** [comment]
Sure @javascriptteacher I'll put in Slack then here after.
