### ISSUE TITLE
Why it's in minified format?

### ISSUE THREAD

**Issue by sanjaypradeep** [javascriptteacher/primary#7]
May I know why the code is in a minified format? 

https://github.com/javascriptteacher/primary/blob/89e92573044d3bc9e4a10955c59e99108567f88f/module/md5/md5.js#L9

**Comment by sanjaypradeep** [comment]
Hey so, the file which is inside the module is downloaded from somewhere? if so, why? We could have do so `npm install <package_name>` to get it install in node modules. isn't it?

**Comment by ilyosjon09** [comment]
Hello @sanjaypradeep! @javascriptteacher is working on this. We will create `package.json` and remove `node_modules` folder from repo. So that, we can install all dependencies using `npm`

**Comment by javascriptteacher** [comment]
**Note:** we need to eventually switch to SHA-2. Let's keep MD5 for now "just to make it work," but shouldn't be hard to switch later.

**Comment by javascriptteacher** [comment]
> Hey so, the file which is inside the module is downloaded from somewhere? if so, why? We could have do so `npm install <package_name>` to get it install in node modules. isn't it?

The project is 1 day old. It was copied over from my Node book. We're currently agreeing that we need to do set it up properly, just like @ilyosjon09 is saying. This will be happening within next few days as we keep updating the code base, cheers ;)

**Comment by sanjaypradeep** [comment]
Thanks for your replied and discussions. Let this issue be open until setup is done.
